# DEMO 5 - Project
# Add application

- job-template:
    name: '{application}-start'
    builders:
      - shared_script_arguments:
         msg: "start."
    publishers:
      - trigger:
          project: '{application}-test'
          threshold: SUCCESS

- job-template:
    name: '{application}-test'
    builders:
      - shared_script_arguments:
         msg: "test."
    publishers:
      - trigger:
          project: '{application}-release'
          threshold: SUCCESS

- job-template:
    name: '{application}-release'
    builders:
      - shared_script_arguments:
         msg: "release"

- project:
    name: applications
    jobs:
      - '{application}-start'
      - '{application}-test'
      - '{application}-release'
    application:
      - foo
      - bar